### ISSUE TITLE
POST returns all existing scripts

### ISSUE THREAD

**Issue by marinamv885** [Team-DBA-TDD-Training/dummy-script-manager#36]
After creating a new script with the POST method all existing scripts are returned. We should return only the newly created script. Please see below the request in Postman:

![Image](https://github.com/user-attachments/assets/8d1930ba-3292-4d0d-b5c2-cd9ec5d85364)

**Comment by anamsadiq** [comment]
@marinamv885 I have done this on purpose. Once we add or edit a script, we need to send the server another request to get the updated list of all scripts on order to refresh the displayed list of scripts.
This way I avoided sending another request, to make the work quicker.
